info:
  app:
    description: '@project.description@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    name: '@project.name@'
    version: '@project.version@'
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    properties:
      hibernate:
        # Esto es vital para evitar el error de metadatos si una conexión tarda
        temp.use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.MariaDBDialect

datasource:
  primary:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/valdivia_cultura_oc_prod?useSSL=false&allowPublicKeyRetrieval=true
    username: dbvaldivia
    password: "Pm8%$21"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  usuarios:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/ragnax_usuario_prod?useSSL=false&allowPublicKeyRetrieval=true
    username: dbvaldivia
    password: "Pm8%$21"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  # Configuración de Hikari (Global o específica)
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
  use-fqn: true


server:
  port: 9191
  servlet:
    context-path: /ccmvaldivia
    session:
      cookie:
        secure: true
    forward-headers-strategy: native

logging:
  file:
    name: logfile
    path: /
management:
  endpoint:
    import jakarta.persistence.s:
      enabled: true
    metrics:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator/${spring.application.name}
      exposure:
        include: logfile,health

swagger:
  configuracion:
    apiinfo:
      titulo: ${spring.application.name} - ${spring.profiles.active}
      version: ${info.app.version}
      descripcion: Microservices ${spring.application.name}-> ${spring.profiles.active}
      termsOfServiceUrl: www.google.com
      license: Swagger license ${spring.profiles.active}
      licenseUrl: www.facebook.com
    documentacion:
      swgg: http://localhost:${server.port}/swagger-ui.html#
      docs: http://localhost:${server.port}/api-docs.yaml
    empresainfo:
      email: ceo@ragnaxsistemas.cl
      nombre: RagnaxSistemas
      url: www.ragnaxsistemas.cl

servicio:
  app:
    generarCartaNotificacion: generarCartaNotificacion
archivo:
  carpeta:
    public: /Users/mac/Workspaces/WorkspaceSanBernardo/com-ragnax-sanbernardo-notificacion/src/main/resources/public_file/
  html:
    nombreCarpetaTemplate: templates/
    nombreHtmlConfirmada: oc_confirmada.html
    nombreHtmlAnulada: oc_anulada.html
    logoEscudo: logos/LogoEsquinaSuperiorIzquierda.png

